version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./userApp/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=userAPP
      - POSTGRES_PASSWORD=qwerty@123
      - POSTGRES_DB=userAPP
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@localhost
      - PGADMIN_DEFAULT_PASSWORD=qwerty@123-+
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"

volumes:
  postgres_data:
  pgadmin_data:
